// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerEconomyServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerEconomyServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<UnityGamingServicesTemplateCloud.PlayerEconomyData> GetPlayerEconomyData()
        {
            return await k_Service.CallModuleEndpointAsync<UnityGamingServicesTemplateCloud.PlayerEconomyData>(
                "UnityGamingServicesTemplateCloud",
                "GetPlayerEconomyData",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task InitializeInventory()
        {
            await k_Service.CallModuleEndpointAsync(
                "UnityGamingServicesTemplateCloud",
                "InitializeInventory",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
