// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class StoreServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public StoreServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<UnityGamingServicesTemplateCloud.PlayerEconomyData> VirtualPurchaseHealthPotion()
        {
            return await k_Service.CallModuleEndpointAsync<UnityGamingServicesTemplateCloud.PlayerEconomyData>(
                "UnityGamingServicesTemplateCloud",
                "VirtualPurchaseHealthPotion",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
