// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.UnityGamingServicesTemplateCloud
{
    public partial class PlayerDataResponse
    {
        public PlayerData PlayerData;
        public PlayerEconomyData EconomyData;
        public bool IsNewPlayer;

        [Preserve]
        public PlayerDataResponse ()
        {
        }
    }
}